### ISSUE TITLE
 Getting "Proxy error: Could not proxy request /favicon.ico from 3000 to http://localhost:4000"

### ISSUE THREAD

**Issue by twilio-akiramoto** [twilio/twilio-voice-notification-app#11]
**Describe the bug**
After starting the application, on the UI I can not change the password. 
When clicking Login, I see the following error on my terminal:

[start:ui] Note that the development build is not optimized.
[start:ui] To create a production build, use npm run build.
[start:ui] 
[start:ui] Proxy error: Could not proxy request /favicon.ico from 3000 to http://localhost:4000.
[start:ui] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
[start:ui] 
[start:ui] Proxy error: Could not proxy request /api/login from 3000 to http://localhost:4000.
[start:ui] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

**How to Reproduce**

clone repo
npm install
changed .env file with my credentials (note: using elephantsql in my setup - e.g. DATABASE_URL=postgres://zyzmfofd:o_pGkqm-Y6RNWC7QAInmoCFSSDD@ruby.db.elephantsql.com:5432/abcde)
npm start

 
**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser Chrome Version 83.0.4103.116
 - Visual Code  1.46.1

**Comment by ricardotwilio** [comment]
Hi @twilio-akiramoto, thank you for reporting this. I was able to reproduce it in my local. 

It is fixed now in https://github.com/twilio/twilio-voice-notification-app/pull/14
